package Assignment_GD1;

import Assignment_model.ReadMoney;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import static java.lang.Thread.sleep;
import java.net.URL;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author dangt
 */
public class BillForm extends javax.swing.JFrame {

    //OrdersManage order = new OrdersManage();
    ReadMoney read = new ReadMoney();
    int timerun = 0;
    float giamGia;
    String textPrice;
    Float price;
    //private Object Tollkit;
    Toolkit toolkit = Toolkit.getDefaultToolkit();
    /**
     * Creates new form OrdersManage
     */
    String ten_ThuNgan;
    String hoa_Don;
    String ten_LoaiNuoc;
    String gia_;
    String so_Luong;
    String ngay_MuaHang;

    public BillForm(String tenThuNgan, String maHoaDon, String tenLoaiNuoc, String gia, String soLuong, String ngayMuaHang) {
        initComponents();
        //Set Icon => JFrame
        URL urlIconMain = OrdersManage.class.getResource("/Assignment_GD1/icon/cup.png");
        Image img = Toolkit.getDefaultToolkit().createImage(urlIconMain);
        this.setIconImage(img);
        //loadData();
//        this.ngayMuaHang = order.danhSach.get(order.index_print).getNgayOrder();
//        this.tenLoaiNuoc =order.danhSach.get(order.index_print).getTenSanPham() ;
//        this.maHoaDon = order.danhSach.get(order.index_print).getMaSanPham() ;
//        this.tenLoaiNuoc = order.danhSach.get(order.index_print).getTenSanPham();
//        this.gia = Float.parseFloat(order.danhSach.get(index).getGia());
//        this.soLuong =Integer.parseInt(order.danhSach.get(index).getSoLuong());
//
//        txtTenThuNgan.setText(ten_ThuNgan);
//        txtMaHoaDon.setText(hoa_Don);
//        txtTenLoaiNuoc.setText(ten_LoaiNuoc);
//        txtNgayMuaHang.setText(ngay_MuaHang);
//        txtSoLuong.setText(String.valueOf(so_Luong));
//        txtGia.setText(String.valueOf(gia_));
        //
        this.ten_ThuNgan = tenThuNgan;
        this.hoa_Don = maHoaDon;
        this.ten_LoaiNuoc = tenLoaiNuoc;
        this.gia_ = gia;
        this.so_Luong = soLuong;
        this.ngay_MuaHang = ngayMuaHang;

//        txtThanhTien.setText(price);
        loadData();
        //btnAdd.doClick();
        //chu_chay();
        TimeRun();
        txtGiamGia.setText("0");
        //jtaMain.setBackground(Color.red);

        //Set Icon => JFrame
    }

    private BillForm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void loadData() {
        txtTenThuNgan.setText(ten_ThuNgan);
        txtMaHoaDon.setText(hoa_Don);
        txtTenLoaiNuoc.setText(ten_LoaiNuoc);
        txtNgayMuaHang.setText(ngay_MuaHang);
        txtSoLuong.setText(so_Luong);
        txtGia.setText(gia_);
        //try {
            if (txtGiamGia.getText().equals("100")) {
                giamGia = Float.parseFloat(txtGia.getText()) * Float.parseFloat(txtSoLuong.getText());
            } else {
                if (Float.parseFloat(txtGiamGia.getText()) > 100 || Float.parseFloat(txtGiamGia.getText()) < 0) {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập lại giảm giá (0<= discount >=100)");
                }
                giamGia = Float.parseFloat("0." + txtGiamGia.getText())
                        * Float.parseFloat(txtGia.getText()) * Float.parseFloat(txtSoLuong.getText());
            }
            //Math.round(rate * 10)
            txtThanhGiam.setText(String.valueOf(giamGia));
            price = (Float.parseFloat(gia_) * Float.parseFloat(so_Luong)) - giamGia;
            textPrice = String.valueOf(price);
            // 110000.0  --> length = 8 | 12003450.0  length = 10
            textPrice = textPrice.substring(0, textPrice.length() - 2);
            txtThanhTien.setText(textPrice);
            txtMoney.setText(read.read_money(textPrice) + "VND");
        //} catch (Exception e) {
            //JOptionPane.showMessageDialog(this, "Tạm thời chưa có voucher giảm giá " + txtGiamGia.getText());
        //}

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        jplLose = new javax.swing.JPanel();
        jlbClose = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        btnAdd1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtThanhGiam = new javax.swing.JLabel();
        txtMoney = new javax.swing.JLabel();
        txtGiamGia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jlbPassWord1 = new javax.swing.JLabel();
        jlbPassWord3 = new javax.swing.JLabel();
        jlbPassWord2 = new javax.swing.JLabel();
        jlbPassWord = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jlbPassWord5 = new javax.swing.JLabel();
        txtTenThuNgan = new javax.swing.JTextField();
        jlbPassWord4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtGia = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txtNgayMuaHang = new javax.swing.JTextField();
        txtTenLoaiNuoc = new javax.swing.JTextField();
        jlbUserName = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txtMaHoaDon = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jlbPassWord6 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblChuChay = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JLabel();

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assignment_GD1/icon/logo.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setBackground(new java.awt.Color(126, 87, 194));
        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Up date");
        btnAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 680, 130, 30));

        jplLose.setBackground(new java.awt.Color(204, 204, 204));
        jplLose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jplLoseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jplLoseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jplLoseMouseExited(evt);
            }
        });
        jplLose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbClose.setBackground(new java.awt.Color(255, 255, 255));
        jlbClose.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jlbClose.setText(" X");
        jlbClose.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jlbCloseFocusGained(evt);
            }
        });
        jlbClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbCloseMouseExited(evt);
            }
        });
        jplLose.add(jlbClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 20, 30));

        jPanel1.add(jplLose, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 60, 30));

        lblTime.setBackground(new java.awt.Color(51, 51, 0));
        lblTime.setFont(new java.awt.Font("Segoe UI Semilight", 1, 20)); // NOI18N
        lblTime.setForeground(new java.awt.Color(0, 153, 0));
        lblTime.setText("00:00 AM");
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 130, 30));

        btnAdd1.setBackground(new java.awt.Color(126, 87, 194));
        btnAdd1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdd1.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd1.setText("Print");
        btnAdd1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 680, 130, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtThanhGiam.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jPanel2.add(txtThanhGiam, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 70, 30));

        txtMoney.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        txtMoney.setForeground(new java.awt.Color(255, 0, 0));
        txtMoney.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMoney.setText("Không nghìn đồng!");
        jPanel2.add(txtMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 420, 30));

        txtGiamGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtGiamGia.setText("000");
        txtGiamGia.setBorder(null);
        txtGiamGia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtGiamGiaFocusGained(evt);
            }
        });
        txtGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiamGiaActionPerformed(evt);
            }
        });
        txtGiamGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGiamGiaKeyPressed(evt);
            }
        });
        jPanel2.add(txtGiamGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 30, 30));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel1.setText("% = ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Wifi password: xincamon");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, -1, -1));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 410, 10));

        jlbPassWord1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbPassWord1.setText("Giảm giá");
        jPanel2.add(jlbPassWord1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 140, 30));

        jlbPassWord3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbPassWord3.setText("Số lượng");
        jPanel2.add(jlbPassWord3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 130, 30));

        jlbPassWord2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbPassWord2.setText("Giá");
        jPanel2.add(jlbPassWord2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 130, 30));

        jlbPassWord.setBackground(new java.awt.Color(0, 0, 0));
        jlbPassWord.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbPassWord.setText("Tên loại nước");
        jPanel2.add(jlbPassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 140, 30));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 130, 10));

        jlbPassWord5.setBackground(new java.awt.Color(0, 0, 0));
        jlbPassWord5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbPassWord5.setText("Ngày mua hàng");
        jPanel2.add(jlbPassWord5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 140, 30));

        txtTenThuNgan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenThuNgan.setBorder(null);
        jPanel2.add(txtTenThuNgan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 300, 30));

        jlbPassWord4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbPassWord4.setText("Thành tiền");
        jPanel2.add(jlbPassWord4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 140, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 130, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 130, 10));

        txtGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtGia.setBorder(null);
        jPanel2.add(txtGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 130, 30));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 130, 10));

        txtNgayMuaHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNgayMuaHang.setBorder(null);
        jPanel2.add(txtNgayMuaHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 120, 30));

        txtTenLoaiNuoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenLoaiNuoc.setBorder(null);
        jPanel2.add(txtTenLoaiNuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 300, 30));

        jlbUserName.setBackground(new java.awt.Color(0, 0, 0));
        jlbUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbUserName.setText("Mã hóa đơn");
        jPanel2.add(jlbUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 140, 30));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 130, 10));

        txtMaHoaDon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaHoaDon.setBorder(null);
        jPanel2.add(txtMaHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 150, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 330, 10));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 330, 10));

        jlbPassWord6.setBackground(new java.awt.Color(0, 0, 0));
        jlbPassWord6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbPassWord6.setText("Tên thu ngân");
        jPanel2.add(jlbPassWord6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 140, 30));

        txtSoLuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSoLuong.setBorder(null);
        jPanel2.add(txtSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 130, 30));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 130, 10));

        lblChuChay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblChuChay.setForeground(new java.awt.Color(51, 153, 0));
        lblChuChay.setText("TIỆM TRÀ HƯƠNG THẢO");
        jPanel2.add(lblChuChay, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 40));

        jLabel5.setText("228 Nguyễn Văn Linh An Khánh Ninh Kiều Cần Thơ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 420, 30));

        txtThanhTien.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jPanel2.add(txtThanhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 130, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 440, 620));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 720));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtGiamGiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiamGiaKeyPressed

    }//GEN-LAST:event_txtGiamGiaKeyPressed

    private void txtGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiamGiaActionPerformed
        //txtUsername.setBackground(Color.red);
    }//GEN-LAST:event_txtGiamGiaActionPerformed

    private void txtGiamGiaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGiamGiaFocusGained

    }//GEN-LAST:event_txtGiamGiaFocusGained

    private void jplLoseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplLoseMouseExited
        // TODO add your handling code here:
        jplLose.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_jplLoseMouseExited

    private void jplLoseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplLoseMouseEntered
        jplLose.setBackground(Color.red);
        //jlbClose.setForeground(Color.white);
    }//GEN-LAST:event_jplLoseMouseEntered

    private void jplLoseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplLoseMouseClicked
        //System.exit(0);
        close();
    }//GEN-LAST:event_jplLoseMouseClicked

    private void jlbCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMouseExited
        // TODO add your handling code here:
        jplLose.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_jlbCloseMouseExited

    private void jlbCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMouseEntered
        // TODO add your handling code here:
        jplLose.setBackground(Color.white);
    }//GEN-LAST:event_jlbCloseMouseEntered

    private void jlbCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMouseClicked
        //System.exit(0);
        close();
    }//GEN-LAST:event_jlbCloseMouseClicked

    private void jlbCloseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jlbCloseFocusGained
        //jplLose.setBackground(Color.red);
        //System.exit(0);
        close();
    }//GEN-LAST:event_jlbCloseFocusGained

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //System.exit(0);
        //close();
        ten_ThuNgan = txtTenThuNgan.getText();
        hoa_Don = txtMaHoaDon.getText();
        ten_LoaiNuoc = txtTenLoaiNuoc.getText();
        ngay_MuaHang = txtNgayMuaHang.getText();
        so_Luong = txtSoLuong.getText();
        gia_ = txtGia.getText();

        JOptionPane.showMessageDialog(this, "Đã cập nhật lại đơn giá!");
        loadData();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        JOptionPane.showMessageDialog(this, "Cần kết nối máy in để in đơn hàng!");
    }//GEN-LAST:event_btnAdd1ActionPerformed

    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        toolkit.getSystemEventQueue().postEvent(closeWindow);
    }

    public void TimeRun() {
        new Thread() {
            public void run() {
                while (timerun == 0) {
                    Calendar cal = new GregorianCalendar();
                    int second = cal.get(Calendar.SECOND);
                    int minute = cal.get(Calendar.MINUTE);
                    int hour = cal.get(Calendar.HOUR_OF_DAY);
                    int AM_PM = cal.get(Calendar.AM_PM);
                    String day_night = "";
                    if (AM_PM == 1) {
                        day_night = "PM";
                    } else {
                        day_night = "AM";
                    }
                    String str = hour + ":" + minute + ":" + second + " " + day_night;
                    lblTime.setText(str);
                }
            }
        }.start();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel jlbClose;
    private javax.swing.JLabel jlbPassWord;
    private javax.swing.JLabel jlbPassWord1;
    private javax.swing.JLabel jlbPassWord2;
    private javax.swing.JLabel jlbPassWord3;
    private javax.swing.JLabel jlbPassWord4;
    private javax.swing.JLabel jlbPassWord5;
    private javax.swing.JLabel jlbPassWord6;
    private javax.swing.JLabel jlbUserName;
    private javax.swing.JPanel jplLose;
    private javax.swing.JLabel lblChuChay;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JLabel txtMoney;
    private javax.swing.JTextField txtNgayMuaHang;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenLoaiNuoc;
    private javax.swing.JTextField txtTenThuNgan;
    private javax.swing.JLabel txtThanhGiam;
    private javax.swing.JLabel txtThanhTien;
    // End of variables declaration//GEN-END:variables

}
