/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Assignment_GD1;


import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import static java.lang.Thread.sleep;
import java.net.URL;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author dangt
 */
public class InforForm extends javax.swing.JFrame {
    
    int timerun = 0;
    boolean admin = false;
    //private Object Tollkit;
    Toolkit toolkit = Toolkit.getDefaultToolkit();  
    /**
     * Creates new form OrdersManage
     */
    public InforForm() {
        initComponents();
        chu_chay();
        TimeRun();
        jtaMain.setEditable(false);
        //jtaMain.setBackground(Color.red);
        
        //Set Icon => JFrame
        URL urlIconMain = OrdersManage.class.getResource("/Assignment_GD1/icon/cup.png");
        Image img = Toolkit.getDefaultToolkit().createImage(urlIconMain);
        this.setIconImage(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        lblChuChay = new javax.swing.JLabel();
        lblChuChay1 = new javax.swing.JLabel();
        jplLose = new javax.swing.JPanel();
        jlbClose = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaMain = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setBackground(new java.awt.Color(51, 51, 0));
        lblTime.setFont(new java.awt.Font("Segoe UI Semilight", 1, 20)); // NOI18N
        lblTime.setForeground(new java.awt.Color(0, 153, 0));
        lblTime.setText("00:00 AM");
        jPanel3.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 130, 44));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setBackground(new java.awt.Color(126, 87, 194));
        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("OK!");
        btnAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 590, 120, 30));

        lblChuChay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblChuChay.setForeground(new java.awt.Color(57, 113, 177));
        lblChuChay.setText(" This software was developed by Tran Huu Dang    ");
        jPanel1.add(lblChuChay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 470, -1));

        lblChuChay1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblChuChay1.setForeground(new java.awt.Color(57, 113, 177));
        lblChuChay1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assignment_GD1/icon/manager.png"))); // NOI18N
        lblChuChay1.setText(" IN4  ");
        jPanel1.add(lblChuChay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 210, -1));

        jplLose.setBackground(new java.awt.Color(59, 59, 59));
        jplLose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jplLoseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jplLoseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jplLoseMouseExited(evt);
            }
        });
        jplLose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbClose.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jlbClose.setForeground(new java.awt.Color(255, 255, 255));
        jlbClose.setText(" X");
        jlbClose.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jlbCloseFocusGained(evt);
            }
        });
        jlbClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbCloseMouseExited(evt);
            }
        });
        jplLose.add(jlbClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 20, 30));

        jPanel1.add(jplLose, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 60, 30));

        jtaMain.setBackground(new java.awt.Color(51, 51, 51));
        jtaMain.setColumns(20);
        jtaMain.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtaMain.setForeground(new java.awt.Color(255, 255, 255));
        jtaMain.setRows(5);
        jtaMain.setText("\n      Phần mềm QUẢN LÍ HÓA ĐƠN ĐIỆN TỬ được xây dựng và phát triển dựa trên NNLT Java.\n\n\t- Phần mềm có giao diện tương thích và hiện đại (dark-mode)\n\n\t- Có giao diện đăng nhập và phân quyền quản trị \n\t       (chỉ Admin mới được chỉnh sửa dữ liệu, ngoài ra chỉ được xem)\n\n\t- Được xây dựng trong khoảng thời gian ngắn vì vậy khó tránh việc chưa tối ưu, \n\t       nhưng sẽ được bảo trì dài hạn\n\n\t- Phần mềm có chương trình bắt lỗi khá tối ưu, \n\t       thao tác gần gũi giúp người dùng không cần dùng chuột quá nhiều\n\n\t- Xin cảm ơn, hãy góp ý để tôi hoàn thiện phần mềm tối ưu hơn!\n\n\t- Chúc bạn có một trải nghiệm tuyệt vời!");
        jtaMain.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(jtaMain);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 810, 410));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assignment_GD1/icon/logo.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 60));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 650));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //System.exit(0);
        close();
    }//GEN-LAST:event_btnAddActionPerformed

    private void jlbCloseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jlbCloseFocusGained
        //jplLose.setBackground(Color.red);
        //System.exit(0);
        close();
    }//GEN-LAST:event_jlbCloseFocusGained

    private void jlbCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMouseClicked
        //System.exit(0);
        close();
    }//GEN-LAST:event_jlbCloseMouseClicked

    private void jlbCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMouseEntered
        // TODO add your handling code here:
        jplLose.setBackground(Color.red);
    }//GEN-LAST:event_jlbCloseMouseEntered

    private void jlbCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMouseExited
        // TODO add your handling code here:
        jplLose.setBackground(new Color(59,59,59));
    }//GEN-LAST:event_jlbCloseMouseExited

    private void jplLoseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplLoseMouseClicked
        //System.exit(0);
        close();
    }//GEN-LAST:event_jplLoseMouseClicked

    private void jplLoseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplLoseMouseEntered
        jplLose.setBackground(Color.red);
        //jlbClose.setForeground(Color.white);
    }//GEN-LAST:event_jplLoseMouseEntered

    private void jplLoseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplLoseMouseExited
        // TODO add your handling code here:
        jplLose.setBackground(new Color(59,59,59));
    }//GEN-LAST:event_jplLoseMouseExited
    
    public void close() {
        WindowEvent closeWindow = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        toolkit.getSystemEventQueue().postEvent(closeWindow);
    }
    //SET USERNAME and PASSWORD
    private String Username = "dangth" ;
    private String Password = "pc04349";

    public String getUsername() {
        return Username;
    }

    public String getPassword() {
        return Password;
    }
    
    public void chu_chay() {
        Thread threadl = new Thread() {
            @Override
            public void run() {
                String txt = " " + lblChuChay.getText() + " ";
                while (true) {
                    txt = txt.substring(1,txt.length() ) + txt.charAt(0);
                    try {
                        sleep(500);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(InforForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                lblChuChay.setText(txt);
                }
            }
            
        };
        threadl.start();
    }
    
    public void TimeRun() {
        new Thread() {
            public void run() {
                while (timerun == 0) {
                    Calendar cal = new GregorianCalendar();
                    int second = cal.get(Calendar.SECOND);
                    int minute = cal.get(Calendar.MINUTE);
                    int hour = cal.get(Calendar.HOUR_OF_DAY);
                    int AM_PM = cal.get(Calendar.AM_PM);
                    String day_night = "";
                    if (AM_PM == 1) {
                        day_night = "PM";
                    } else {
                        day_night = "AM";
                    }
                    String str = hour + ":" + minute + ":" + second + " " + day_night;
                    lblTime.setText(str);
                }
            }
        }.start();

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InforForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InforForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InforForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InforForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InforForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbClose;
    private javax.swing.JPanel jplLose;
    private javax.swing.JTextArea jtaMain;
    private javax.swing.JLabel lblChuChay;
    private javax.swing.JLabel lblChuChay1;
    private javax.swing.JLabel lblTime;
    // End of variables declaration//GEN-END:variables

    
}
