package Assignment_GD1;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import static java.lang.Thread.sleep;
import java.net.URL;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author dangt
 */
public class Main_Form extends javax.swing.JFrame {

    int timerun = 0;
    String error = null;
    boolean admin = false;
    //private Object Tollkit;
    Toolkit toolkit = Toolkit.getDefaultToolkit();

    /**
     * Creates new form OrdersManage
     */
    public Main_Form() {
        initComponents();
        chu_chay();
        TimeRun();
        jplHideLogin.setVisible(false);
        lblHideTitle.setVisible(false);
        lblHideLoading.setVisible(false);
        chkRememberme.setSelected(true);
        jlbHide.setVisible(false);
        txtErrorPassWord.setVisible(false);
        txtErrorUserName.setVisible(false);
        txtPassword.setEchoChar('●');
        //Set Icon => JFrame
        URL urlIconMain = OrdersManage.class.getResource("/Assignment_GD1/icon/cup.png");
        Image img = Toolkit.getDefaultToolkit().createImage(urlIconMain);
        this.setIconImage(img);
        //SET ICON MESSAGE
        URL urlIconMessageI = OrdersManage.class.getResource("/Assignment_GD1/icon/letter-i.png");
        Image imgMessageI = Toolkit.getDefaultToolkit().createImage(urlIconMessageI);
        //this.setIconImage(img);
        //
        URL urlIconAlert = OrdersManage.class.getResource("/Assignment_GD1/icon/alert.png");
        Image imgAlert = Toolkit.getDefaultToolkit().createImage(urlIconAlert);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jplHideLogin = new javax.swing.JPanel();
        lblHideTitle = new javax.swing.JLabel();
        lblHideLoading = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        chkRememberme = new javax.swing.JCheckBox();
        btnAdd = new javax.swing.JButton();
        txtErrorPassWord = new javax.swing.JLabel();
        txtErrorUserName = new javax.swing.JLabel();
        jlbUserName = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jplLose = new javax.swing.JPanel();
        jlbClose = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jlbPassWord = new javax.swing.JLabel();
        lblChuChay = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblChuChay1 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jlbSupport = new javax.swing.JLabel();
        jlbHide = new javax.swing.JLabel();
        jlbShow = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setBackground(new java.awt.Color(51, 51, 0));
        lblTime.setFont(new java.awt.Font("Segoe UI Semilight", 1, 20)); // NOI18N
        lblTime.setForeground(new java.awt.Color(0, 153, 0));
        lblTime.setText("00:00 AM");
        jPanel3.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 130, 44));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jplHideLogin.setBackground(new java.awt.Color(51, 51, 51));
        jplHideLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHideTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblHideTitle.setForeground(new java.awt.Color(51, 153, 0));
        lblHideTitle.setText("TIỆM TRÀ HƯƠNG THẢO");
        jplHideLogin.add(lblHideTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 450, 90));

        lblHideLoading.setFont(new java.awt.Font("Segoe UI Semilight", 1, 22)); // NOI18N
        lblHideLoading.setForeground(new java.awt.Color(102, 102, 255));
        lblHideLoading.setText("loading...");
        jplHideLogin.add(lblHideLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, 60));

        jPanel1.add(jplHideLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 650));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 300, 10));

        chkRememberme.setBackground(new java.awt.Color(51, 51, 51));
        chkRememberme.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkRememberme.setForeground(new java.awt.Color(255, 255, 255));
        chkRememberme.setText("Sign in with admin permissions?");
        chkRememberme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRemembermeActionPerformed(evt);
            }
        });
        jPanel1.add(chkRememberme, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 230, 23));

        btnAdd.setBackground(new java.awt.Color(126, 87, 194));
        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Login");
        btnAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 120, 30));

        txtErrorPassWord.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        txtErrorPassWord.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorPassWord.setText("Required field");
        jPanel1.add(txtErrorPassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 180, 17));

        txtErrorUserName.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        txtErrorUserName.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorUserName.setText("Required field");
        jPanel1.add(txtErrorUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 180, 17));

        jlbUserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbUserName.setForeground(new java.awt.Color(57, 113, 177));
        jlbUserName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assignment_GD1/icon/id-card.png"))); // NOI18N
        jlbUserName.setText("Username");
        jlbUserName.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jlbUserNameComponentMoved(evt);
            }
        });
        jPanel1.add(jlbUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 140, 40));

        txtUsername.setBackground(new java.awt.Color(51, 51, 51));
        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setBorder(null);
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
        });
        txtUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsernameMouseClicked(evt);
            }
        });
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsernameKeyPressed(evt);
            }
        });
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 300, 30));

        jplLose.setBackground(new java.awt.Color(59, 59, 59));
        jplLose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jplLoseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jplLoseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jplLoseMouseExited(evt);
            }
        });
        jplLose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbClose.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jlbClose.setForeground(new java.awt.Color(255, 255, 255));
        jlbClose.setText(" X");
        jlbClose.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jlbCloseFocusGained(evt);
            }
        });
        jlbClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbCloseMouseExited(evt);
            }
        });
        jplLose.add(jlbClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 20, 30));

        jPanel1.add(jplLose, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 60, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 300, 10));

        jlbPassWord.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbPassWord.setForeground(new java.awt.Color(102, 102, 102));
        jlbPassWord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assignment_GD1/icon/password.png"))); // NOI18N
        jlbPassWord.setText("Password");
        jPanel1.add(jlbPassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 294, 140, 30));

        lblChuChay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblChuChay.setForeground(new java.awt.Color(57, 113, 177));
        lblChuChay.setText(" This software was developed by Tran Huu Dang    ");
        jPanel1.add(lblChuChay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 470, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assignment_GD1/icon/google-plus (2).png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assignment_GD1/icon/facebook.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, -1, -1));

        lblChuChay1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblChuChay1.setForeground(new java.awt.Color(57, 113, 177));
        lblChuChay1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assignment_GD1/icon/businessman (1).png"))); // NOI18N
        lblChuChay1.setText(" LOGIN  ");
        jPanel1.add(lblChuChay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 210, -1));

        btnReset.setBackground(new java.awt.Color(126, 87, 194));
        btnReset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Infor");
        btnReset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnResetMouseExited(evt);
            }
        });
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 120, 30));

        jlbSupport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbSupport.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jlbSupport, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, 320, 30));

        jlbHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assignment_GD1/icon/hide.png"))); // NOI18N
        jlbHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbHideMouseClicked(evt);
            }
        });
        jPanel1.add(jlbHide, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, -1));

        jlbShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assignment_GD1/icon/show.png"))); // NOI18N
        jlbShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbShowMouseClicked(evt);
            }
        });
        jPanel1.add(jlbShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, -1));

        txtPassword.setBackground(new java.awt.Color(51, 51, 51));
        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(null);
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 300, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assignment_GD1/icon/logo.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 60));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 650));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
//        txtUsername.setText("");
//        txtPassword.setText("");
//        txtErrorPassWord.setText("");
//        txtErrorUserName.setText("");
//        txtUsername.requestFocus();
        Infor_Form infor = new Infor_Form();
        infor.setVisible(true);
    }//GEN-LAST:event_btnResetActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        JOptionPane.showMessageDialog(this, "Tính năng chưa hỗ trợ!");
//        JOptionPane.showMessageDialog(this, "Tính năng chưa hỗ trợ!", 0, "Thông báo", "/Assignment_GD1/icon/letter-i.png");
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        JOptionPane.showMessageDialog(this, "Tính năng chưa hỗ trợ!");
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        jlbPassWord.setForeground(new Color(102, 102, 102));
        jlbUserName.setForeground(new Color(57, 113, 177));


    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        //jlbUsername.setForeground(Color.blue);
//        jlbUserName.setForeground(new Color(57,113,177));
//        jlbPassWord.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_txtUsernameFocusGained

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        ImageIcon icon = new ImageIcon("icon/login.png");
        if (txtPassword.getText().equals("")) {
           //JOptionPane.showMessageDialog(this, "Vui lòng nhập Password!");
            //txtUsername.setBackground(Color.white);
            //txtPassword.setBackground(Color.pink);
            //txtErrorPassWord.setText("Required field");
            //txtErrorUserName.setText("");
            txtErrorPassWord.setVisible(true);
            txtPassword.requestFocus();
        }
        if (txtUsername.getText().equals("")) {
            //JOptionPane.showMessageDialog(this, "Vui lòng nhập Username!");
            //txtUsername.setBackground(Color.pink);
            //txtErrorUserName.setText("Required field");
            txtErrorUserName.setVisible(true);
            txtUsername.requestFocus();
        } 
         else {
            //txtErrorUserName.setText("");
            //txtErrorPassWord.setText("");
            txtErrorUserName.setVisible(false);
            txtErrorPassWord.setVisible(false);
            //txtPassword.setBackground(Color.white);
            if (txtUsername.getText().equals(getUsername()) && txtPassword.getText().equals(getPassword())) {
                //JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");

                //JOptionPane.showMessageDialog(this, "Đăng nhập thành công", "Login",JOptionPane.INFORMATION_MESSAGE, icon);
                //System.exit(0);
                if (chkRememberme.isSelected()) {
                    jplHideLogin.setVisible(true);
                    lblHideTitle.setVisible(true);
                    lblHideLoading.setVisible(true);
                    JOptionPane.showMessageDialog(this, "Đã đăng nhập với quyền quản trị!");
                    admin = true;
                } else {
                    jplHideLogin.setVisible(true);
                    lblHideTitle.setVisible(true);
                    lblHideLoading.setVisible(true);
                    JOptionPane.showMessageDialog(this, "Đã đăng nhập với quyền người xem!");
                    
                    admin = false;
                }
                OrdersManage order = new OrdersManage(admin);
                order.setVisible(true);
                close();
            } else {
                JOptionPane.showMessageDialog(this, "Username hoặc Password không chính xác!");
                txtUsername.requestFocus();
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void chkRemembermeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRemembermeActionPerformed
        if (txtUsername.getText().equals(""))
            txtUsername.requestFocus();
        else
            txtPassword.requestFocus();
    }//GEN-LAST:event_chkRemembermeActionPerformed

    private void jlbCloseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jlbCloseFocusGained
        //jplLose.setBackground(Color.red);
        System.exit(0);
    }//GEN-LAST:event_jlbCloseFocusGained

    private void jlbCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jlbCloseMouseClicked

    private void jlbCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMouseEntered
        // TODO add your handling code here:
        jplLose.setBackground(Color.red);
    }//GEN-LAST:event_jlbCloseMouseEntered

    private void jlbCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMouseExited
        // TODO add your handling code here:
        jplLose.setBackground(new Color(59, 59, 59));
    }//GEN-LAST:event_jlbCloseMouseExited

    private void jplLoseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplLoseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jplLoseMouseClicked

    private void jplLoseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplLoseMouseEntered
        jplLose.setBackground(Color.red);
        //jlbClose.setForeground(Color.white);
    }//GEN-LAST:event_jplLoseMouseEntered

    private void jplLoseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplLoseMouseExited
        // TODO add your handling code here:
        jplLose.setBackground(new Color(59, 59, 59));
    }//GEN-LAST:event_jplLoseMouseExited

    private void txtUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jlbPassWord.setForeground(new Color(57, 113, 177));
            jlbUserName.setForeground(new Color(102, 102, 102));
            txtPassword.requestFocus();
        }
    }//GEN-LAST:event_txtUsernameKeyPressed


    private void btnResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseEntered
        jlbSupport.setText("Hãy click nó nếu bạn cần trợ giúp từ chúng tôi!");
    }//GEN-LAST:event_btnResetMouseEntered

    private void btnResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseExited
        // TODO add your handling code here:
        jlbSupport.setText("");
    }//GEN-LAST:event_btnResetMouseExited

    private void jlbHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbHideMouseClicked
//        txtPassword.setVisible(true);
//        jlbShowPassword.setVisible(false);
//        //password_temp = txtPassword.getText();
        jlbHide.setVisible(false);
        txtPassword.requestFocus();
//        //jlbHidePassword.setVisible(false);
//        //jlbShowPassword.setVisible(false);
//        txtPassword.setText(password_temp);
        jlbShow.setVisible(true);
        txtPassword.setEchoChar('●');
        jlbUserName.setForeground(new Color(102, 102, 102));
        jlbPassWord.setForeground(new Color(57, 113, 177));
        txtErrorPassWord.setVisible(false);
    }//GEN-LAST:event_jlbHideMouseClicked

    private void jlbShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbShowMouseClicked
        txtPassword.setEchoChar((char)0);
        txtPassword.requestFocus();
//        password_temp = txtPassword.getText();
//        txtPassword.setVisible(false);
//        jlbShowPassword.setText(txtPassword.getText());
//        jlbShowPassword.setVisible(true);
//        txtPassword.setText("");
        jlbHide.setVisible(true);
        jlbShow.setVisible(false);
        jlbUserName.setForeground(new Color(102, 102, 102));
        jlbPassWord.setForeground(new Color(57, 113, 177));
        txtErrorPassWord.setVisible(false);
        //btnAdd.doClick();
    }//GEN-LAST:event_jlbShowMouseClicked

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnAdd.doClick();
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed

    }//GEN-LAST:event_txtPasswordActionPerformed

    private void jlbUserNameComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jlbUserNameComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbUserNameComponentMoved

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        // TODO add your handling code here:
        jlbUserName.setForeground(new Color(102, 102, 102));
        jlbPassWord.setForeground(new Color(57, 113, 177));
        txtErrorPassWord.setVisible(false);
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void txtUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsernameMouseClicked
        jlbPassWord.setForeground(new Color(102, 102, 102));
        jlbUserName.setForeground(new Color(57, 113, 177));
        txtErrorUserName.setVisible(false);
    }//GEN-LAST:event_txtUsernameMouseClicked

    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        toolkit.getSystemEventQueue().postEvent(closeWindow);
    }
    //SET USERNAME and PASSWORD
    private String Username = "dangth";
    private String Password = "pc04349";

    public String getUsername() {
        return Username;
    }

    public String getPassword() {
        return Password;
    }

    public void chu_chay() {
        Thread threadl = new Thread() {
            @Override
            public void run() {
                String txt = " " + lblChuChay.getText() + " ";
                while (true) {
                    txt = txt.substring(1, txt.length()) + txt.charAt(0);
                    try {
                        sleep(500);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Main_Form.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    lblChuChay.setText(txt);
                }
            }

        };
        threadl.start();
    }

    public void TimeRun() {
        new Thread() {
            public void run() {
                while (timerun == 0) {
                    Calendar cal = new GregorianCalendar();
                    int second = cal.get(Calendar.SECOND);
                    int minute = cal.get(Calendar.MINUTE);
                    int hour = cal.get(Calendar.HOUR_OF_DAY);
                    int AM_PM = cal.get(Calendar.AM_PM);
                    String day_night = "";
                    if (AM_PM == 1) {
                        day_night = "PM";
                    } else {
                        day_night = "AM";
                    }
                    String str = hour + ":" + minute + ":" + second + " " + day_night;
                    lblTime.setText(str);
                }
            }
        }.start();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnReset;
    private javax.swing.JCheckBox chkRememberme;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlbClose;
    private javax.swing.JLabel jlbHide;
    private javax.swing.JLabel jlbPassWord;
    private javax.swing.JLabel jlbShow;
    private javax.swing.JLabel jlbSupport;
    private javax.swing.JLabel jlbUserName;
    private javax.swing.JPanel jplHideLogin;
    private javax.swing.JPanel jplLose;
    private javax.swing.JLabel lblChuChay;
    private javax.swing.JLabel lblChuChay1;
    private javax.swing.JLabel lblHideLoading;
    private javax.swing.JLabel lblHideTitle;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel txtErrorPassWord;
    private javax.swing.JLabel txtErrorUserName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
